### ISSUE TITLE
Can't get working

### ISSUE THREAD

**Issue by bobbieshaban** [simoncchu/REPdenovo#2]
Hi, 

I'm trying to get REPdeonovo working on my system but I am coming across errors, such as the one below.

I've used python 2.6.6 and python 2.7.3 and I have all the dependencies installed byt when I run main.py I get the following error.

[shabanb@melb-compute05 121]$ python /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py -c Assembly -g config.txt -r file.txt
rm: cannot remove `./repdenovo/Asm_*': No such file or directory
rm -r ./repdenovo/Asm_*
rm ./repdenovo/*.fa
rm: cannot remove`./repdenovo/_.fastq': No such file or directory
rm ./repdenovo/_.fastq
Working on 30mer now...
Highest 30mer frequency is 0
Traceback (most recent call last):
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 397, in <module>
    main_func(scommand,sfconfig,sfreads_list)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 360, in main_func
    bpaired, sfleft_reads, sfright_reads, sfsingle_reads)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/Assembly.py", line 146, in assembly
    with open(sconcate,"r") as fin:
IOError: [Errno 2] No such file or directory: './repdenovo/30mer.temp_contigs.fa'

My config file is like this

MIN_REPEAT_FREQ 10
RANGE_ASM_FREQ_DEC 2
RANGE_ASM_FREQ_GAP 0.8
K_MIN 30
K_MAX 50
K_INC 10
K_DFT 30
READ_LENGTH 250
READ_DEPTH 60
THREADS 60
ASM_NODE_LENGTH_OFFSET -1
MIN_CONTIG_LENGTH 100
IS_DUPLICATE_REPEATS 0.85
COV_DIFF_CUTOFF 0.5
MIN_SUPPORT_PAIRS 20
MIN_FULLY_MAP_RATIO 0.2
TR_SIMILARITY 0.85
JELLYFISH_PATH /usr/local/appl/bio/jellyfish/bin/
VELVET_PATH /usr/local/appl/bio/velvet/bin/
BWA_PATH /usr/local/appl/bio/bwa/bin/
SAMTOOLS_PATH /usr/local/appl/bio/samtools/bin/
REFINER_PATH /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/
CONTIGS_MERGER_PATH /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/
OUTPUT_FOLDER ./repdenovo/
VERBOSE 1

and my raw reads file is like this
[shabanb@melb-compute05 121]$ cat file.txt
/ssd/Prawn_18_R1_val_1.fq 1 550 50
/ssd/Prawn_18_R2_val_2.fq 1 550 50

Thank you for your help,
Bobbie

**Comment by simoncchu** [comment]
Hi Bobbie,

It seems errors happen on the "kmer counting" step. From the output, I think there is "dumped_30mers.txt" file under the OUTPUT_FOLDER right? Would you please check whether there is content inside this file? 

If not, can you remove this file, and re-run and see whether same error happen. 

Best,
Chong

**Comment by bobbieshaban** [comment]
Hi!

Thanks for that, the file dumped_30mers.txt was empty, so I deleted it and re ran the program and this is the error I receive. It seems to be a jelly fish error but jellyfish is working correctly when I run it independently and I remove the --bf-size and -F parameters

/usr/local/appl/bio/jellyfish/bin/jellyfish count -s 500M -C -m 30 -t 15 -o ./repdenovo/mer_counts.jf /ssd/Prawn_18_R1_val_1.fq /ssd/Prawn_18_R2_val_2.fq

What version of jellyfish should I be running? I am running
[shabanb@melb-compute04 ~]$ jellyfish --version
jellyfish 1.1.11

We haven't had a need to upgrade but I will upgrade to 2.0 and give it a go.

[shabanb@melb-compute05 121]$ python /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py -c Assembly -g config.txt -r file.txt
rm: cannot remove `./repdenovo/Asm_*': No such file or directory
rm -r ./repdenovo/Asm_*
rm ./repdenovo/*.fa
rm: cannot remove`./repdenovo/_.fastq': No such file or directory
rm ./repdenovo/_.fastq
Working on 30mer now...
Counting kmers...
Running command: /usr/local/appl/bio/jellyfish/bin/jellyfish count -s 500M --bf-size 30M -C -m 30 -t 15 -o ./repdenovo/mer_counts.jf -F 2 /ssd/Prawn_18_R1_val_1.fq /ssd/Prawn_18_R2_val_2.fq...
count: unrecognized option '--bf-size'
Use --usage or --help for some help
Running command: /usr/local/appl/bio/jellyfish/bin/jellyfish dump -L 600 -o ./repdenovo/dumped_30mers.txt ./repdenovo/mer_counts.jf...
terminate called after throwing an instance of 'jellyfish::compacted_hash::ErrorReading'
  what():  './repdenovo/mer_counts.jf': File truncated
Highest 30mer frequency is 0
Traceback (most recent call last):
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 397, in <module>
    main_func(scommand,sfconfig,sfreads_list)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 360, in main_func
    bpaired, sfleft_reads, sfright_reads, sfsingle_reads)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/Assembly.py", line 146, in assembly
    with open(sconcate,"r") as fin:
IOError: [Errno 2] No such file or directory: './repdenovo/30mer.temp_contigs.fa'

**Comment by bobbieshaban** [comment]
Yep, that seems to have fixed it, the latest version of jellyfish. Thanks!
