### ISSUE TITLE
Contigs merger

### ISSUE THREAD

**Issue by bobbieshaban** [simoncchu/REPdenovo#3]
Hi,

When I run contigsMerger I get the following error
[shabanb@melb-compute05 121]$ /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/ContigsMerger-v0.1.9/ContigsMerger
Arrange error! 0 6

While running within the program, the following command doesn't produce any output

/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/ContigsMerger-v0.1.9/ContigsMerger -s 0.2 -i1 -6.0 -i2 -6.0 -x 15 -k 10 -t 15 -m 1 -o ./repOut22/contigs.fa_no_dup.fa.merge.info ./repOut22/contigs.fa_no_dup.fa > ./repOut22/contigs.fa_no_dup.fa.merged.fa

The software continues on but fails when it tries to create a bam file

Running command: Running command: samtools faidx ./repOut22/contigs.fa_no_dup.fa.merged.fa ...
[bwa_index] Pack FASTA... [bns_fasta2bntseq] Failed to allocate 0 bytes at bntseq.c line 303: Success
[E::bwa_idx_load_from_disk] fail to locate the index files
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
[bam_header_read] EOF marker is absent. The input is probably truncated.
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
Running command: /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/TERefiner_1 -P -b ./repOut22/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam -r ./repOut22/contigs.fa_no_dup.fa.merged.fa -o ./repOut22/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -c 0.85 ...
Index file not found, now create it!!!
Index file cannot be created!!!
Bamtools ERROR: could not open input BAM file: ./repOut22/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam

I'm thinking because the ontigs.fa_no_dup.fa.merged.fa.no_dup.fa is empty.

Is there a way to overcome this? I have the original_contigs_before_merging.fa file, which is 27Mb in size. 

any help would be greatly appreciated,

thankyou,
bobbie

**Comment by simoncchu** [comment]
Hi Bobbie, 

Very sorry for the late reply, I am travelling and just get your email.

It seems you are working on a quite repetitive genome. The original contigs is 27Mb in size, while for human that is less than 3Mb. It seems some error happen when working on the large number of contigs. I will check this and let you know.

One suggestion I will make is set the "MIN_REPEAT_FREQ" parameter in the configuration file a larger number, like 200, which will be suitable for a more repetitive genome. We set this value as the approximate copy number of the repeats we are focus on. By default this value is 10, which will generate lots of contigs if the genome is quite repetitive. 

Best,
Chong

**Comment by bobbieshaban** [comment]
Hi,

Performed a run of RepDenovo as requested and it died at the same stage. This time the original contigs before merging is now 1.4 Mb.

Attached below is the error. Samtools and BWA are accessible via the command line and it seems to have created the index, but it can't access it after that.

Is there anyway I can continue without running the whole program? Would I be able to run merge contigs.py on the original unmerged contigs?

`Running command: Running command: samtools faidx ./repOutNew/contigs.fa ...
[bwa_index] Pack FASTA... 0.02 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.36 seconds elapse.
[bwa_index] Update BWT... 0.01 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.18 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index ./repOutNew/contigs.fa
[main] Real time: 1.911 sec; CPU: 0.601 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 3972 sequences (1212393 bp)...
[M::mem_process_seqs] Processed 3972 reads in 7.933 CPU sec, 7.926 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -a ./repOutNew/contigs.fa ./repOutNew/contigs.fa
[main] Real time: 8.134 sec; CPU: 7.973 sec
[samopen] SAM header is present: 3972 sequences.
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
Running command: /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/TERefiner_                                                                                                                                                             1 -P -b ./repOutNew/contigs.fa.itself.sort.bam -r ./repOutNew/contigs.fa -o ./re                                                                                                                                                             pOutNew/contigs.fa_no_dup.fa -c 0.9 ...
Index file not found, now create it!!!
Index file cannot be created!!!
Bamtools ERROR: could not open input BAM file: ./repOutNew/contigs.fa.itself.sor                                                                                                                                                             t.bam
rm: cannot remove`./repOutNew/contigs.fa.itself.sort.bam': No such file or dire                                                                                                                                                             ctory
rm: cannot remove `./repOutNew/contigs.fa.itself.sort.bam.bai': No such file or                                                                                                                                                              directory
Running command: /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/ContigsMer                                                                                                                                                             ger-v0.1.9/ContigsMerger -s 0.2 -i1 -6.0 -i2 -6.0 -x 15 -k 10 -t 15 -m 1 -o ./re                                                                                                                                                             pOutNew/contigs.fa_no_dup.fa.merge.info ./repOutNew/contigs.fa_no_dup.fa > ./rep                                                                                                                                                             OutNew/contigs.fa_no_dup.fa.merged.fa ...
Running command: Running command: samtools faidx ./repOutNew/contigs.fa_no_dup.f                                                                                                                                                             a.merged.fa ...
[bwa_index] Pack FASTA... [bns_fasta2bntseq] Failed to allocate 0 bytes at bntse                                                                                                                                                             q.c line 303: Success
[E::bwa_idx_load_from_disk] fail to locate the index files
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
[bam_header_read] EOF marker is absent. The input is probably truncated.
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
Running command: /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/TERefiner_                                                                                                                                                             1 -P -b ./repOutNew/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam -r ./repOutNe                                                                                                                                                             w/contigs.fa_no_dup.fa.merged.fa -o ./repOutNew/contigs.fa_no_dup.fa.merged.fa.n                                                                                                                                                             o_dup.fa -c 0.85 ...
Index file not found, now create it!!!
Index file cannot be created!!!
Bamtools ERROR: could not open input BAM file: ./repOutNew/contigs.fa_no_dup.fa.                                                                                                                                                             merged.fa.itself.sort.bam
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.sa': No such file                                                                                                                                                              or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.bwt': No such file                                                                                                                                                              or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.ann': No such file                                                                                                                                                              or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.amb': No such file                                                                                                                                                              or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam':                                                                                                                                                              No such file or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam.ba                                                                                                                                                             i': No such file or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.fai': No such file                                                                                                                                                              or directory
Running command: Running command: samtools faidx ./repOutNew/contigs.fa_no_dup.f                                                                                                                                                             a.merged.fa.no_dup.fa ...
open: No such file or directory
[_razf_open] fail to open ./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[fai_build] fail to open the FASTA file ./repOutNew/contigs.fa_no_dup.fa.merged.                                                                                                                                                             fa.no_dup.fa
open: No such file or directory
[_razf_open] fail to open ./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[fai_build] fail to open the FASTA file ./repOutNew/contigs.fa_no_dup.fa.merged.                                                                                                                                                             fa.no_dup.fa
[bwa_index] fail to open file './repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup                                                                                                                                                             .fa' : No such file or directory
[E::bwa_idx_load_from_disk] fail to locate the index files
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
[bam_header_read] EOF marker is absent. The input is probably truncated.
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
Running command: /data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/TERefiner_                                                                                                                                                             1 -P -b ./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.sort.bam -r                                                                                                                                                              ./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -o ./repOutNew/contigs.fa_n                                                                                                                                                             o_dup.fa.merged.fa.no_dup.fa.no_contained.fa -c 0.85 -g ...
Index file not found, now create it!!!
Index file cannot be created!!!
Bamtools ERROR: could not open input BAM file: ./repOutNew/contigs.fa_no_dup.fa.                                                                                                                                                             merged.fa.no_dup.fa.itself.sort.bam
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.sa': No                                                                                                                                                              such file or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.pac': No                                                                                                                                                              such file or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.bwt': No                                                                                                                                                              such file or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.ann': No                                                                                                                                                              such file or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.amb': No                                                                                                                                                              such file or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.s                                                                                                                                                             ort.bam': No such file or directory
rm: cannot remove `./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.s                                                                                                                                                             ort.bam.bai': No such file or directory
rm: cannot remove`./repOutNew/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai': No                                                                                                                                                              such file or directory
Traceback (most recent call last):
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 397,                                                                                                                                                              in <module>
    main_func(scommand,sfconfig,sfreads_list)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/main.py", line 376,                                                                                                                                                              in main_func
    local_THREADS, RM_DUP_BF_MERGE_CUTOFF, RM_DUP_AF_MERGE_CUTOFF)
  File "/data/Bioinfo/bioinfo-proj-bobbie/newProgs/REPdenovo/MergeContigs.py", l                                                                                                                                                             ine 88, in merge_contigs
    os.rename(foutput,fout_folder+"contigs.fa")
OSError: [Errno 2] No such file or directory
`

**Comment by simoncchu** [comment]
Hi @bobbieshaban ,

Is it possible for you to send me one copy of the contigs before merging?  I'd like to debug to check what's wrong there.

**Comment by simoncchu** [comment]
Hi @bobbieshaban,

I just tried the merger part with the contigs generated from human, and it works fine on our server. I wonder whether you can send me the one you generated and let me have a test?

**Comment by bobbieshaban** [comment]
Hi,

Thank you for this, the before merging contigs are attached. It’s about 1.5 Mb in size.

Thankyou for your help.

Bobbie.

**Comment by simoncchu** [comment]
@bobbieshaban , I didn't find the attached file. Would you please double check? Or you can send me email: chong.chu@uconn.edu

**Comment by simoncchu** [comment]
@bobbieshaban , also would you please check the samtools version? Is it v1.3.1 or later version? If not, then the sorting may failed. As the latest version of samtools have different parameter format from the early version.

**Comment by bobbieshaban** [comment]
Hi,

I can confirm it is samtools 1.20, I will upgrade and test again.

Thankyou.
