### ISSUE TITLE
how to set the read txt file

### ISSUE THREAD

**Issue by bzvew** [simoncchu/REPdenovo#8]
Hello. I use short reads from http://www.ebi.ac.uk/ena/data/view/SRX040486 as input (RepARK paper data),
[sample_configuration_10X.txt](https://github.com/Reedwarbler/REPdenovo/files/1269524/sample_configuration_10X.txt)
[reads.txt](https://github.com/Reedwarbler/REPdenovo/files/1269525/reads.txt)

 and for the configuration and read txt, I use the settings and the running log as denovo.txt as the attachment. But the result file is only 60k, I think I may set something wrong. Can you have a look at those file? Especially I do not know how to set the information about insert. Thanks!

**Comment by bzvew** [comment]
[Uploading denovo.txt…]()

**Comment by bzvew** [comment]
[denovo.txt](https://github.com/Reedwarbler/REPdenovo/files/1269539/denovo.txt)

**Comment by simoncchu** [comment]
Hi @bzvew ,
Can u change the "MIN_REPEAT_FREQ 10" (first line in the config file) to a smaller value, like 5, and try again. It's better to use a different output folder (set the "OUTPUT_FOLDER ./test/" in the config file).
